sonar.projectKey=Caixa_CI_CD
sonar.organization=caiogoulart9
sonar.projectName=Caixa_CI_CD
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.java.source=17
sonar.java.target=17
sonar.sourceEncoding=UTF-8

sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/CaixaApplication.java
